name             'base-server'
maintainer       'Maruti Nandan Pandya'
maintainer_email 'mnandan.pandya@gmail.com'
license          'All rights reserved'
description      'Installs/Configures base-server'
long_description 'Installs/Configures base-server'
version          '0.1.0'
