---
driver:
  name: vagrant
  # customize:
  #   memory: 1024
  #   cpus: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.11.18
  environments_path: ../../environments
  client_rb:
    environment: development
  cookbook_path: ../cookbooks
  roles_path: ../../roles


platforms:
  - name: ubuntu-14.04
    driver:
      network:
        - ["private_network", { type: "dhcp" }]
        - ["forwarded_port", {guest: 8080, host: 8081}]

suites:
  - name: jenkins
    data_bags_path: "../../data_bags"
    # encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"
    run_list:
     - recipe[apt]
     - recipe[myjenkins::jenkins]
    # includes:
    #   - 'ubuntu-14.04'
    attributes:
      jenkins:
        master:
          install_method: 'war'
          source: 'http://mirrors.jenkins-ci.org/war-stable/1.651.3/jenkins.war'
      app:
        environment: 'development'
        mysql:
          hostname: '10.0.2.2'
